service: resize-image-lambda
description: The AWS CF Serverless template for resize-image-${opt:stage}
frameworkVersion: '=1.27'

custom:
  headers:
  - Content-Type
  - X-Amz-Date
  - Authorization
  - X-Api-Key
  - X-Amz-Security-Token
  - X-Amz-User-Agent
  - Accept
  - X-Client-Source
  - Client-Type

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  deploymentBucket: applications.${opt:stage}
  stackTags:
    EnvironmentTag: ${opt:stage}
    VersionTag: "1.0"
  environment:
    Environment: ${opt:stage}
    ALLOWED_RESOLUTIONS: 800x600
    BUCKET: ${opt:stage}-vitrines-files
    URL: https://${opt:stage}-vitrines-files.s3-eu-west-1.amazonaws.com
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "s3:ListBucket"
    - "s3:GetObject"
    - "s3:PutObject"
    Resource:
      Fn::Join:
      - ""
      - - "arn:aws:s3:::"
        - ${opt:stage}
        - "-vitrines-files"
        - "/*"

#plugins:
#- serverless-webpack

package:
  exclude:
  - .serverless
  - .gitignore
  - Architecture.png
  - aws
  - cbm_serverless-image-resize.iml
  - diagram.svg
#  - node_modules
  - package.json
  - serverless-2010-09-09.yml
  - README.md
  - buildspec.yml
  - commitlint.config.js
#  - index.js
  - package-lock.json
  - sequenceDiagram
  - serverless.yml


functions:
  ResizeImage:
    name: resize-image-lambda-${opt:stage}-ResizeImage
    description: Resizes images
    memorySize: 1024
    timeout: 30
    handler: index.handler
    events:
    - http:
        path: /v1/resize-image
        method: GET
        private: false
        cors:
          origins:
          - '*'
          headers: ${self:custom.headers}
          allowCredentials: false

#resources:
#  Resources:
#    ImageBucket:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: ${opt:stage}-vitrines-files
#        AccessControl: PublicRead
#        WebsiteConfiguration:
#          IndexDocument: index.html
#          RoutingRules:
#          - RedirectRule:
#              HostName: foo.amazonaws.com
#              HttpRedirectCode: "307"
#              Protocol: https
#              ReplaceKeyPrefixWith: dev/v1/resize-image?key=
#            RoutingRuleCondition:
#              HttpErrorCodeReturnedEquals: "404"
