service: ${self:custom.project.name}

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "s3:ListBucket"
    - "s3:GetObject"
    - "s3:GetObjectAcl"
    Resource:
      Fn::Join:
      - ""
      - - "arn:aws:s3:::"
        - "dev-vitrines-files"
        - "/*"
  - Effect: "Allow"
    Action:
    - "s3:ListBucket"
    - "s3:PutObject"
    - "s3:DeleteObject"
    - "s3:GetObjectAcl"
    - "s3:ListBucketMultipartUploads"
    - "s3:ListMultipartUploadParts"
    - "s3:PutObject"
    - "s3:PutObjectAcl"
    - "s3:PutObjectTagging"
    - "s3:PutObjectVersionAcl"
    - "s3:PutObjectVersionTagging"
    Resource:
      Fn::Join:
      - ""
      - - "arn:aws:s3:::"
        - "dev-vitrines-files"
        - "/*"


#plugins:
#- serverless-webpack

package:
  exclude:
  - .serverless
  - .gitignore
  - package.json
  - README.md
  - serverless.yml

functions:
  sharpImage:
    description: Resizes images
    memorySize: 1024
    timeout: 30
    handler: index.handler
    events:
    - s3:
        bucket: "dev-vitrines-files"
        event: s3:ObjectCreated:*
