version: 0.2

phases:
  install:
    commands:
      - yarn install
  build:
    commands:
#TODO      - yarn sls:$ENV
      - yarn build


artifacts:
  files:
    - serverless.yml
  discard-paths: yes

cache:
  paths:
    - '/node_modules/**/*'
