version: 0.2

phases:
  install:
    commands:
      - yarn install
  build:
    commands:
      - yarn sls:remove:$ENV
      - yarn sls:$ENV

artifacts:
  files:
    - serverless.yml
  discard-paths: yes

cache:
  paths:
    - '/node_modules/**/*'
